- hosts: localhost
  become: true
  tasks:    
    - name: Download the installation script
      get_url:
         url: "https://downloads.nordcdn.com/apps/linux/install.sh"
         dest: /tmp/nordvpn-install.sh
      tags:
        - arch
        - deb

    - name: Run the installation
      command: sh /tmp/nordvpn-install.sh
      tags:
        - arch
        - deb
