- hosts: localhost
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  tasks:
    - name: Download the .deb package
      get_url:
          url: https://repo.protonvpn.com/debian/dists/stable/main/binary-all/protonvpn-stable-release_1.0.3_all.deb
          dest: /tmp/protonvpn.deb
      tags:
        - deb

    - name: Install the downloaded package
      apt:
         deb: /tmp/protonvpn.deb
      tags:
        - deb

    - name: Install the CLI vpn client
      apt:
        pkg:
          - protonvpn-cli
      tags:
        - deb
