- hosts: localhost
  tasks:
    - name: Install GIMP
      become: true
      apt:
        pkg:
            - gimp
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install GIMP
      become: true
      community.general.pacman:
        name:
          - gimp
        state: present
      tags:
        - arch
