- hosts: localhost
  become: true
  tasks:
    - name: Install GIMP
      apt:
        pkg:
          - gimp
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install GIMP
      pacman:
        name:
          - gimp
        state: latest
        update_cache: true
      tags:
        - arch
