- hosts: localhost
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  tasks:
    - name: Install GIMP
      apt:
        pkg:
            - gimp
      tags:
        - deb

    - name: Install GIMP
      community.general.pacman:
        name:
          - gimp
      tags:
        - arch
