- hosts: localhost
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  tasks:
    - name: Install graphics tools
      apt:
        pkg:
          - feh
          - geeqie
      tags:
        - deb

    - name: Install graphics tools
      community.general.pacman:
        name:
          - gimp
      tags:
        - arch
