- hosts: localhost
  become: true
  tasks:
    - name: Install graphics tools
      apt:
        pkg:
          - feh
          - geeqie
          - gimp
          - imagemagick

        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install graphics tools
      community.general.pacman:
        name:
          - feh
          - geeqie
          - gimp
          - imagemagick
        state: latest
        update_cache: true
      tags:
        - arch
