- hosts: localhost
  tasks:
    - name: Install graphics tools
      become: true
      apt:
        pkg:
          - feh
          - geeqie
      tags:
        - deb

    - name: Install graphics tools
      become: true
      community.general.pacman:
        name:
          - gimp
        state: present
      tags:
        - arch
