- hosts: all
  become: true
  tasks:
    - name: Add vivaldi repository key
      apt_key:
         url: https://repo.vivaldi.com/stable/linux_signing_key.pub
      tags:
        - deb

    - name: Check if repository exists
      stat:
          path: /etc/apt/sources.list.d/vivaldi.list
      register:
          vivaldi_repo
      tags:
        - deb

    - name: Add repository
      apt_repository:
          repo: "deb https://repo.vivaldi.com/stable/deb/ stable main"
          state: present
          filename: vivaldi
      when:
        - vivaldi_repo.stat.exists == False
      tags:
        - deb

    - name: Install package
      become: true
      apt:
        name: vivaldi-stable
        state: latest
      tags:
        - deb

    - name: Install vivaldi browser
      community.general.pacman:
        name: vivaldi
        state: present
      tags:
        - arch



    
