- hosts: localhost
  vars:
    go_version: "1.21.4"
    sys_architecture: "amd64"
  tasks:
    - name: Download Go binary
      become: true
      get_url:
        url: "https://golang.org/dl/go{{ go_version }}.linux-{{ sys_architecture }}.tar.gz"
        dest: "/tmp/go.tar.gz"

    - name: Extract Go archive
      become: true
      become_user: root
      ansible.builtin.unarchive:
        src: "/tmp/go.tar.gz"
        dest: "/usr/local"
        remote_src: yes

    - name: Add Go Environment variables to shell profile
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "{{ item }}"
        create: yes
      with_items:
        - "export PATH=$PATH:/usr/local/go/bin"
        - "export GOPATH=$HOME/go"

    - name: Install go-pls server
      command: go install golang.org/x/tools/gopls@latest

    - name: Cleanup the downloaded archive
      become: true
      command: rm /tmp/go.tar.gz 
