- hosts: localhost
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  vars:
    go_version: "1.21.4"
    sys_architecture: "amd64"
  tasks:
    - name: Download Go binary
      get_url:
        url: "https://golang.org/dl/go{{ go_version }}.linux-{{ sys_architecture }}.tar.gz"
        dest: "/tmp/go.tar.gz"
      tags:
        - deb

    - name: Extract Go archive
      ansible.builtin.unarchive:
        src: "/tmp/go.tar.gz"
        dest: "/usr/local"
        remote_src: yes
      tags:
        - deb

    - name: Install Go from the repository
      community.general.pacman:
        name: go
        state: present
      tags:
        - arch

    - name: Add Go Environment variables to shell profile
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "{{ item }}"
        create: yes
      with_items:
        - "export PATH=$PATH:/usr/local/go/bin"
        - "export GOPATH=$HOME/go"
      tags:
        - arch
        - deb

    - name: Install go-pls server
      environment:
         PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
      command: go install golang.org/x/tools/gopls@latest
      tags:
        - arch
        - deb

    - name: Cleanup the downloaded archive
      command: rm /tmp/go.tar.gz
      tags:
        - deb
