- hosts: localhost
  become: yes
  vars:
    go_version: "1.21.3"
    sys_architecture: "amd64"
  tasks:
    - name: Download Go binary
      get_url:
        url: "https://golang.org/dl/go{{ go_version }}.linux-{{ sys_architecture }}.tar.gz"
        dest: "/tmp/go.tar.gz"
      register: download_result
      changed_when: download_result.changed

    - name: Extract Go archive
      ansible.builtin.unarchive:
        src: "/tmp/go.tar.gz"
        dest: "/tmp/local"
        remote_src: yes
      when: download_result.changed

    - name: Add Go Environment variables to shell profile
      lineinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        line: "{{ item }}"
        create: yes
      with_items:
        - "export PATH=$PATH:/usr/local/go/bin"
        - "export GOPATH=$HOME/go"

    - name: Ensure Go is in the PATH immediately
      command: "source {{ ansible_env.HOME }}/.zshrc"
      when: download_result.changed