- hosts: localhost
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  tasks:
    - name: Install Python 3.11
      apt:
        pkg: 
          - python3.11
          - python3-pip
          - ipython3
      tags:
        - deb
        - python
        - pip

    - name: Upgrade pip for Python 3.11
      command: python3.11 -m pip install --upgrade pip
      tags:
        - deb
        - upgrade-pip

    - name: Install Python
      community.general.pacman:
        name:
          - python3
          - python-pip
          - ipython
      tags:
        - arch

    - name: Install python-lsp-server[all] for PLS support in Emacs
      command: python3 -m pip install python-lsp-server[all]
      tags:
        - deb
        - python-lsp-server

    - name: Install python-lsp-server
      community.general.pacman:
        name:
          - python-lsp-server
      tags:
        - arch
