- hosts: localhost
  tasks:
    - name: Install Python 3.11
      become: true
      apt:
        name: python3.11
        state: latest
      tags:
        - python

    - name: Install pip for Python 3.11
      become: true
      apt:
        name: python3.11-pip
        state: latest
      tags:
        - pip

    - name: Upgrade pip for Python 3.11
      become: true
      command: python3.11 -m pip install --upgrade pip
      tags:
        - upgrade-pip

    - name: Install python-lsp-server[all] for PLS support in Emacs
      become: true
      command: python3.11 -m pip install python-lsp-server[all]
      tags:
        - python-lsp-server
