- hosts: localhost
  become: true
  tasks:
    - name: Install Python 3.13
      apt:
        pkg: 
          - python3.13
          - python3-pip
          - ipython3
          - python3-pylsp
        state: latest
        update_cache: true
      tags:
        - deb
        - python
        - pip

    - name: Install Python
      pacman:
        name:
          - python3
          - python-pip
          - ipython
        state: latest
        update_cache: true
      tags:
        - arch

    - name: Install python-lsp-server
      pacman:
        name:
          - python-lsp-server
        state: latest
        update_cache: true
      tags:
        - arch
