- hosts: localhost
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  tasks:
    - name: Install libvirt
      apt:
        pkg:
           - libvirtd
           - qemu-kvm
           - virt-manager
           - qemu-img
           - qemu-utils
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install libvirt
      pacman:
        name:
          - libvirt
          - qemu-full
          - virt-manager
        state: latest
        update_cache: true
      tags:
        - arch
    
    - name: Start libvirt
      service: libvirtd
      status: started
