- hosts: localhost
  tasks:
    - name: Install libvirt
      become: true
      apt:
        pkg:
           - libvirtd
           - qemu-kvm
           - virt-manager
           - qemu-img
           - qemu-utils
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install libvirt
      become: true
      community.general.pacman:
        name:
          - libvirt
          - qemu-full
          - virt-manager
        state: present
      tags:
        - arch
    
    - name: Start libvirt
      service: libvirtd
      status: started
