- hosts: localhost
  become: true
  tasks:
    - name: Install libvirt
      apt:
        pkg:
           - libvirtd
           - qemu-kvm
           - virt-manager
           - qemu-img
           - qemu-utils
           - vagrant
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install libvirt
      pacman:
        name:
          - libvirt
          - qemu-full
          - virt-manager
          - vagrant
        state: latest
        update_cache: true
      tags:
        - arch
    
    - name: Start libvirt
      ansible.builtin.service: 
        name: libvirtd
        state: started
        enabled: yes
