- hosts: all
  become: true
  vars:
    docker_compose_version: "2.23.0"
  tasks:
    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install dependencies
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
      tags:
        - deb

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
      tags:
        - deb

    - name: "Docker: install"
      apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: latest
        update_cache: true
      tags:
        - deb
    
    - name: "Install docker-compose version: {{ docker_compose_version }}"
      command: 'curl -L "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose'
      tags:
        - deb

    - name: Add execute permissions
      file:
        path: /usr/local/bin/docker-compose
        mode: +x
      tags:
        - deb

    - name: Add current user to the docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
      tags:
        - deb

    - name: Install docker
      pacman:
        name: docker
        state: latest
        update_cache: true
      tags:
        - arch

    - name: Install docker-compose
      pacman:
        name: docker-compose
        state: latest
        update_cache: true
      tags:
        - arch
