- hosts: localhost
  tasks:
    - name: Install
      become: true
      apt:
        pkg:
           - mc
           - htop
           - neomutt
           - zsh
           - cryptsetup
           - openssh-client
           - openssh-server
        state: latest
        update_cache: true

    - name: Copy zshrc config
      copy:
        src: ../configs/dotfiles/.zshrc
        dest: ~/

    - name: Copy mutt config
      copy:
        src: ../configs/dotfiles/.mutt
        dest: ~/
        recursive: yes
       