- hosts: localhost
  tasks:
    - name: Install
      become: true
      apt:
        pkg:
           - mc
           - htop
           - neomutt
           - zsh
           - cryptsetup
        state: latest
        update_cache: true

    - name: Copy zshrc config
      copy:
        src: ./config/.zshrc
        dest: ~/