- hosts: localhost
  become: yes
  tasks:
    - name: Install CLI tools
      apt:
        pkg:
           - mc
           - htop
           - neomutt
           - zsh
           - cryptsetup
           - openssh-client
           - openssh-server
           - net-tools
           - aria2
           - lsof
           - wireguard-tools
           - make
           - cmake
           - stlink-tools
           - coreutils
           - bind9-dnsutils
           - cosign
           - tmux
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install CLI tools
      pacman:
        name:
          - mc
          - htop
          - neomutt
          - zsh
          - cryptsetup
          - openssh
          - net-tools
          - aria2
          - lsof
          - xorg-xinput
          - wireguard-tools
          - make
          - cmake
          - stlink
          - coreutils
          - dnstuls
          - cosign
          - csvlens
          - tmux
        state: latest
        update_cache: true
        upgrade: true
      tags:
        - arch

    - name: Enable autostart of ssh server
      ansible.builtin.service:
        name: sshd
        state: started
        enabled: yes
      tags:
        - arch


    - name: Copy zshrc config
      copy:
        src: ../configs/dotfiles/.zshrc
        dest: ~/
      tags:
        - arch
        - deb
 
    - name: Copy mutt config
      synchronize:
        src: ../configs/dotfiles/.mutt
        dest: ~/
      tags:
        - arch
        - deb
       
