- hosts: localhost
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  tasks:
    - name: Install cups
      apt:
        pkg:
          - cups
      tags:
        - deb

    - name: Install cups
      community.general.pacman:
        name:
          - cups
      tags:
        - arch
