- hosts: localhost
  become: true
  tasks:
    - name: Install cups
      apt:
        pkg:
          - cups
          - hplip
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install cups
      pacman:
        name:
          - cups
          - hplip
        state: latest
        update_cache: true
      tags:
        - arch
