- hosts: localhost
  tasks:
    - name: Install syncthing
      become: true
      apt:
        pkg:
          - syncthing
        state: latest
        update_cache: true

    - name: Get current username
      set_fact:
          current_user: "{{ ansible_env.USER }}"
    
    - name: Enable syncthing autostart on login
      become: true
      systemd:
        name: syncthing@{{ current_user }}
        state: started
        enabled: true
      
