- hosts: localhost
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  tasks:
    - name: Install syncthing
      apt:
        pkg:
          - syncthing
      tags:
        - deb

    - name: Install syncthing
      community.general.pacman:
        name:
          - syncthing
      tags:
        - arch

    - name: Get current username
      set_fact:
          current_user: "{{ ansible_env.USER }}"
      tags:
        - deb
        - arch
    
    - name: Enable syncthing autostart on login
      systemd:
        name: syncthing@{{ current_user }}
        state: started
        enabled: true
      tags:
        - deb
        - arch
        

    
      
