- hosts: localhost
  become: true
  tasks:
    - name: Install syncthing
      apt:
        pkg:
          - syncthing
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install syncthing
      pacman:
        name:
          - syncthing
        state: latest
        update_cache: true
      tags:
        - arch

    - name: Get current username
      set_fact:
          current_user: "{{ ansible_env.USER }}"
      tags:
        - deb
        - arch
    
    - name: Enable syncthing autostart on login
      systemd:
        name: syncthing@{{ current_user }}
        state: started
        enabled: true
      tags:
        - deb
        - arch
        

    
      
