- hosts: localhost
  become_user: root

  tasks:
    - name: Download VeraCrypt Debian package
      get_url:
        url: "https://launchpad.net/veracrypt/trunk/1.26.7/+download/veracrypt-1.26.7-Debian-12-amd64.deb"
        dest: "/tmp/veracrypt-1.26.7-Debian-12-amd64.deb"

    - name: Install VeraCrypt using dpkg
      become: true
      apt:
        deb: "/tmp/veracrypt-1.26.7-Debian-12-amd64.deb"
        state: present

    - name: Remove downloaded files
      file:
        path: "/tmp/{{ item }}"
        state: absent
      loop:
        - "veracrypt-1.26.7-Debian-12-amd64.deb"