- hosts: localhost
  become: true
  tasks:
    - name: Download VeraCrypt Debian package
      get_url:
        url: "https://github.com/veracrypt/VeraCrypt/releases/download/VeraCrypt_1.26.24/veracrypt-1.26.24-Debian-12-amd64.deb"
        dest: "/tmp/veracrypt.deb"
      tags:
        - deb

    - name: Install VeraCrypt using dpkg
      apt:
        deb: "/tmp/veracrypt.deb"
      tags:
        - deb

    - name: Remove downloaded files
      file:
        path: "/tmp/veracrypt.deb"
        state: absent
      tags:
        - deb

    - name: Install VeraCrypt
      pacman:
        name:
          - veracrypt
        state: latest
        update_cache: true
      tags:
        - arch
