- hosts: localhost
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  tasks:
    - name: Install dependencies
      apt:
        name:
          - cmake
          - pkg-config
          - libfreetype6-dev
          - libfontconfig1-dev
          - libxcb-xfixes0-dev
          - python3
          - libxcb-shape0-dev
          - libxcb-xkb-dev
          - libxkbcommon-x11-dev
          - libxcb1-dev
          - libxcb-keysyms1-dev
          - libxrandr-dev
          - libxi-dev
          - cargo
      tags:
        - deb


    - name: Build and install Alacritty
      command: cargo install alacritty
      tags:
        - deb

    - name: Install alacritty
      community.general.pacman:
        name: alacritty
        state: present
      tags:
        - arch

    - name: Copy alacritty config
      copy:
         src: ../configs/dotfiles/alacritty.yml
         dest: ~/.config
      tags:
        - arch
        - deb
         
