- hosts: localhost
  tasks:
    - name: Check if cargo installed
      shell: command -v cargo
      register: cargo_exists
      ignore_errors: yes
    
    - name: Download installer
      when: cargo_exists is failed
      get_url:
          url: https://sh.rustup.rs
          dest: /tmp/sh.rustup.rs
          mode: '0755'
          force: 'yes'
      tags:
        - rust

    - name: install rust/cargo
      when: cargo_exists is failed
      shell: /tmp/sh.rustup.rs -y
      tags:
        - rust

    - name: install alacritty
      command: 'cargo install alacritty'

    - name: Clone a repo with color themes
      git:
           repo: https://github.com/mikalai-dev/alacritty-theme.git
           dest: ~/.config/alacritty/themes
    
    - name: Copy alacritty config
      copy:
        src: ../configs/alacritty.yml
        dest: ~/.config/alacritty/
