- hosts: localhost
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"

  tasks:
    - name: Download the package
      get_url:
        url: https://desktop.briarproject.org/debs/jammy/briar-desktop-ubuntu-22.04.deb
        dest: /tmp/briar-desktop.deb
      tags:
        - deb

    - name: Install the package
      apt:
        deb: /tmp/briar-desktop.deb
        state: present
      tags:
        - deb

    - name: Cleanup
      file:
        state: absent
        path: /tmp/briar-desktop.deb
      tags:
        - deb

    - name: Create directory for briar
      file:
        path: /usr/share/briar
        state: directory
      tags:
        - arch

    - name: Download the Briar jar
      get_url:
        url: https://desktop.briarproject.org/jars/linux/briar-desktop-linux.jar
        dest: /usr/share/briar/briar-desktop-linux.jar
      tags:
        - arch

    - name: Create executing script for briar desktop
      copy:
        content: |
          #!/bin/bash
          java -jar /usr/share/briar/briar-desktop-linux.jar
        dest: /usr/bin/briar
        mode: 0755
      tags:
        - arch
