- hosts: localhost
  become_user: root
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  tasks:
    - name: Ensure the target font directory exists
      become: true
      file:
        path: /usr/share/fonts/source-code-pro
        state: directory
      tags:
        - deb
        - arch

    - name: Download Source Code Pro font archive
      get_url:
        url: "https://github.com/adobe-fonts/source-code-pro/releases/download/2.042R-u%2F1.062R-i%2F1.026R-vf/TTF-source-code-pro-2.042R-u_1.062R-i.zip"
        dest: "/tmp/source-code-pro.zip"
      tags:
        - deb
        - arch

    - name: Extract the font archive
      become: true
      unarchive:
        src: "/tmp/source-code-pro.zip"
        dest: "/usr/share/fonts/source-code-pro"
        remote_src: yes
      tags:
        - deb
        - arch

    - name: Run fc-cache to update font cache
      command: fc-cache --force
      tags:
        - deb
        - arch
