- hosts: localhost
  tasks:
    - name: Install viking
      become: true
      apt:
        pkg:
          - viking
          - josm
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install viking
      community.general.pacman:
        name: viking
        state: present
      become: true
      tags:
        - arch

    - name: Install josm
      community.general.pacman:
        name:
          - josm
          - jdk-openjdk
      become: true
      tags:
        - arch

    - name: Backup for the default josm start script
      command: mv /usr/bin/josm /usr/bin/josm-backup 
      become: true
      tags:
        - arch

    - name: Creating new /usr/bin/josm
      ansible.builtin.file:
        path: /usr/bin/josm
        state: touch
        mode: 0755
      become: true
      tags:
        - arch

    - name: Adding of workaround for josm bug https://bugs.archlinux.org/task/78707
      lineinfile:
        path: /usr/bin/josm
        line: |
          #!/bin/bash
          java -jar /usr/share/java/josm/josm.jar
      become: true
      tags:
        - arch
