- hosts: all
  become_user: root

  tasks:
    - name: Install i3 window manager
      become: true
      apt:
        pkg:
           - i3-wm
           - i3blocks
           - i3lock
           - rofi
        state: latest
        update_cache: true
    
    - name: Remove config directory
      command: rm -rf ~/.config/i3

    - name: Download i3 config
      command: git clone 'https://github.com/mikalai-dev/i3_config.git' ~/.config/i3

