- hosts: all
  become: true
  tasks:
    - name: Install i3 window manager
      apt:
        pkg:
          - i3-wm
          - i3blocks
          - i3lock
          - rofi
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install i3 window manager
      pacman:
        name:
          - i3-wm
          - i3blocks
          - i3lock
          - rofi
        state: latest
        update_cache: true
      tags:
        - arch
        
    
    - name: Remove config directory
      command: rm -rf ~/.config/i3
      tags:
        - arch
        - deb

    - name: Copy i3 config
      synchronize:
        src: ../configs/i3_config/
        dest: ~/.config/i3
      tags:
        - arch
        - deb

