- hosts: all
  become_user: root
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  tasks:
    - name: Install i3 window manager
      apt:
        pkg:
          - i3-wm
          - i3blocks
          - i3lock
          - rofi
      tags:
        - deb

    - name: Install i3 window manager
      community.general.pacman:
        name:
          - i3-wm
          - i3blocks
          - i3lock
          - rofi
      tags:
        - arch
        
    
    - name: Remove config directory
      command: rm -rf ~/.config/i3
      tags:
        - arch
        - deb

    - name: Copy i3 config
      synchronize:
        src: ../configs/i3_config/
        dest: ~/.config/i3
      tags:
        - arch
        - deb

