- hosts: all
  become_user: root

  tasks:
    - name: Install i3 window manager
      become: true
      apt:
        pkg:
           - i3-wm
           - i3blocks
           - i3lock
           - rofi
        state: latest
        update_cache: true
    
    - name: Remove config directory
      command: rm -rf ~/.config/i3

    - name: Copy i3 config
      copy:
        src: ../configs/i3_config/
        dest: ~/.config/i3
        recursive: yess

