- hosts: localhost
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  tasks:
    - name: Install KeepassXC
      apt:
        pkg:
            - keepassxc
      tags:
        - deb

    - name: Install keepassxc from repository
      community.general.pacman:
        name: keepassxc
      tags:
        - arch

        
