- hosts: localhost
  become: true
  tasks:
    - name: Install KeepassXC
      apt:
        pkg:
            - keepassxc
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install keepassxc from repository
      community.general.pacman:
        name: keepassxc
        state: latest
        update_cache: true
      tags:
        - arch

        
