- hosts: localhost
  become_user: root
  tasks:
    - name: Install KeepassXC
      become: true
      apt:
        pkg:
            - keepassxc
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install keepassxc from repository
      become: true
      community.general.pacman:
        name: keepassxc
        state: present
      tags:
        - arch

        
