- hosts: localhost
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  tasks:
    - name: Install spotify client
      apt:
        pkg:
          - spotify-client
      tags:
        - deb

    - name: Install spotify client for manjaro
      community.general.pacman:
        name: spotify-launcher
        state: present
      tags:
        - arch

    - name: Install vlc player
      apt:
        pkg:
          - vlc
      tags:
        - deb

    - name: Install vlc player
      community.general.pacman:
        name: vlc
      tags:
        - arch

    - name: Install Calibre
      apt:
        pkg:
          - calibre
      tags:
        - deb

    - name: Install Calibre
      community.general.pacman:
        name: calibre
      tags:
        - arch

    - name: Install documents viewer
      apt:
        pkg:
          - evince
      tags:
        - deb

    - name: Install documents viewer
      community.general.pacman:
        name: evince
      tags:
        - arch

