- hosts: localhost
  become: true
  tasks:
    - name: Install spotify client
      apt:
        pkg:
          - spotify-client
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install spotify client for manjaro
      community.general.pacman:
        name: spotify-launcher
        state: latest
        update_cache: true
      tags:
        - arch

    - name: Install vlc player
      apt:
        pkg:
          - vlc
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install vlc player
      community.general.pacman:
        name: vlc
        state: latest
        update_cache: true
      tags:
        - arch

    - name: Install Calibre
      apt:
        pkg:
          - calibre
      tags:
        - deb

    - name: Install Calibre
      community.general.pacman:
        name: calibre
        state: latest
        update_cache: true
      tags:
        - arch

    - name: Install documents viewer
      apt:
        pkg:
          - evince
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install documents viewer
      community.general.pacman:
        name: evince
        state: latest
        update_cache: true
      tags:
        - arch

