- hosts: localhost
  become: true
  tasks:
    - name: Install spotify client
      apt:
        pkg:
          - spotify-client
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install spotify client for manjaro
      pacman:
        name: spotify-launcher
        state: latest
        update_cache: true
      tags:
        - arch

    - name: Install vlc player
      apt:
        pkg:
          - vlc
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install vlc player
      pacman:
        name: vlc
        state: latest
        update_cache: true
      tags:
        - arch

    - name: Install Calibre
      apt:
        pkg:
          - calibre
      tags:
        - deb

    - name: Install Calibre
      pacman:
        name: calibre
        state: latest
        update_cache: true
      tags:
        - arch

    - name: Install documents viewer
      apt:
        pkg:
          - evince
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install documents viewer
      pacman:
        name: evince
        state: latest
        update_cache: true
      tags:
        - arch

    - name: Install Museeks audioplayer
      block:
        - name: Create the destination directory
          file:
            path: /opt/museeks
            state: directory
            
        - name: Download AppImage
          get_url:
            url: https://github.com/martpie/museeks/releases/download/0.13.1/museeks-x86_64.AppImage
            dest: /opt/museeks/museeks-x86_64.AppImage
            mode: '0755'

        - name: Link to the /usr/bin
          file:
            src: /opt/museeks/museeks-x86_64.AppImage
            dest: /usr/bin/museeks
            state: link
            force: yes

        - name: Chnage mode to executable
          file:
            path: /usr/bi//museeks
            mode: 'a+x'
    tags:
      - arch
      - deb

