- hosts: localhost
  become_user: root
  tasks:
    - name: Install spotify client
      become: true
      apt:
        pkg:
          - spotify-client
        state: latest
        update_cache: true

    - name: Install vlc player
      become: true
      apt:
        pkg:
          - vlc
        state: latest
        update_cache: true
    