- hosts: localhost
  become_user: root
  tasks:
    - name: Install spotify client
      become: true
      apt:
        pkg:
          - spotify-client
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install spotify client for manjaro
      become: true
      community.general.pacman:
        name: spotify-launcher
        state: present
      tags:
        - arch

    - name: Install vlc player
      become: true
      apt:
        pkg:
          - vlc
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install vlc player
      become: true
      community.general.pacman:
        name: vlc
        state: present
      tags:
        - arch

    - name: Install Calibre
      become: true
      apt:
        pkg:
          - calibre
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install Calibre
      become: true
      community.general.pacman:
        name: calibre
        state: present
      tags:
        - arch

    - name: Install documents viewer
      become: true
      apt:
        pkg:
          - evince
      tags:
        - deb

    - name: Install documents viewer
      become: true
      community.general.pacman:
        name: evince
        state: present
      tags:
        - arch

