- hosts: all
  become: true
  tasks:
    - name: Create destination directory for the app
      file:
        path: /opt/mindomo
        state: directory
      tags:
        - arch
        - deb

    - name: Download Mindomo desktop free AppImage
      get_url:
        url: https://www.mindomo.com/download/10.8/Mindomo_v.10.8.2_x64.AppImage
        dest: /opt/mindomo/mindomo.AppImage
      tags:
        - arch
        - deb

    - name: Link the AppImage to /usr/bin
      file:
        src: /opt/mindomo/mindomo.AppImage
        dest: /usr/bin/mindomo
        state: link
        force: yes
      tags:
        - arch
        - deb

    - name: Change mode to executable
      file:
        path: /usr/bin/mindomo
        mode: 'a+x'
      tags:
        - arch
        - deb
        
