- hosts: localhost
  become: true
  tasks:
    - name: Download Proton Mail Bridge for debian
      get_url:
        url: https://proton.me/download/bridge/protonmail-bridge_3.7.1-1_amd64.deb
        dest: /tmp/protonmail-bridge.deb
      tags:
        - deb

    - name: Install the downloaded package
      apt:
        deb: /tmp/protonmail-bridge.deb
      tags:
        - deb

    - name: Make directory for building package
      become_user: "{{ lookup('env', 'USER') }}"
      file:
        path: /tmp/bridge
        state: directory
      tags:
        - arch

    - name: Download PKGBUILD
      become_user: "{{ lookup('env', 'USER') }}"
      get_url:
        url: https://proton.me/download/bridge/PKGBUILD
        dest: /tmp/bridge/PKGBUILD
      tags:
        - arch

    - name: Build and install Proton Mail Bridge package
      become_user: "{{ lookup('env', 'USER') }}"
      command: makepkg -sri --noconfirm
      args:
        chdir: /tmp/bridge
      tags:
        - arch

    - name: Cleanup
      file:
        path: /tmp/bridge
        state: absent
      tags:
        - arch
