- hosts: localhost
  become: true
  tasks:
    - name: Ensure keyrings directory exists
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'
      tags:
        - deb

    - name: Download Signal GPG key
      get_url:
        url: https://updates.signal.org/desktop/apt/keys.asc
        dest: /etc/apt/keyrings/signal.asc
        mode: '0644'
      tags:
        - deb

    - name: Add Signal APT repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/signal.asc] https://updates.signal.org/desktop/apt xenial main"
        state: present
      tags:
        - deb

    - name: Install Signal Messenger
      apt:
        name: signal-desktop
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install Signal Messenger
      pacman:
        name: signal-desktop
        state: latest
        update_cache: true
      tags:
        - arch

