- hosts: localhost
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  tasks:
    - name: Add Signal APT repository key
      apt_key:
        url: https://updates.signal.org/desktop/apt/keys.asc
      register: key_result
      tags:
        - deb

    - name: Add Signal APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://updates.signal.org/desktop/apt xenial main"
      when: key_result.changed
      tags:
        - deb

    - name: Install Signal Messenger
      apt:
        name: signal-desktop
      tags:
        - deb

    - name: Install Signal Messenger
      community.general.pacman:
        name: signal-desktop
      tags:
        - arch
      
