- hosts: localhost
  become: true
  tasks:
    - name: Download Slack for debian
      get_url:
        url: https://downloads.slack-edge.com/releases/linux/4.35.131/prod/x64/slack-desktop-4.35.131-amd64.deb
        dest: /tmp/slack.deb
      tags:
        - deb

    - name: Install the downloaded package
      apt:
        deb: /tmp/slack.deb
      tags:
        - deb

    - name: Install prerequisites for arch
      pacman:
        name:
          - git
          - base-devel
        update_cache: true
      tags:
        - arch

    - name: Clone the AUR repository
      git:
        repo: https://aur.archlinux.org/slack-desktop.git
        dest: /tmp/slack-desktop
      tags:
        - arch

    - name: Build and install Slack package
      command: makepkg -sri
      args:
        chdir: ~/slack-desktop
      register: makepkg_result
      tags:
        - arch

    - name: Confirm package installation
      pause:
        prompt: "Proceed with installing Slack package? (Y/n)"
      when: "'y' not in makepkg_result.stdout"
      tags:
        - arch

    - name: Install Slack using yay
      command: yay -S slack-desktop
      register: yay_result
      tags:
        - arch

    - name: Confirm Slack installation
      pause:
        prompt: "Proceed with installing Slack using yay? (Y/n)"
      when: "'y' not in yay_result.stdout"
      tags:
        - arch

    - name: Cleanup
      file:
        path: "/tmp/slack-desktop"
        state: absent
      tags:
        - arch
