- hosts: localhost
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  tasks:
    - name: Install thunderbird
      apt:
        pkg:
           - thunderbird
      tags:
        - deb

    - name: Install thunderbird
      community.general.pacman:
        name: thunderbird
      tags:
        - arch
      
