- hosts: localhost
  become: true
  tasks:
    - name: Install thunderbird
      apt:
        pkg:
           - thunderbird
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install thunderbird
      community.general.pacman:
        name: thunderbird
        state: latest
        update_cache: true
      tags:
        - arch
      
