- hosts: localhost
  become: true
  tasks:
    - name: Install torbrowser
      apt:
        pkg:
           - torbrowser-launcher
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install torbrowser
      pacman:
        name: torbrowser-launcher
        state: latest
        update_cache: true
      tags:
        - arch
  
