- hosts: localhost
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  tasks:
    - name: Install torbrowser
      apt:
        pkg:
           - torbrowser-launcher
      tags:
        - deb

    - name: Install torbrowser
      community.general.pacman:
        name: torbrowser-launcher
      tags:
        - arch
  
