- hosts: localhost
  tasks:
    - name: Install torbrowser
      become: true
      apt:
        pkg:
           - torbrowser-launcher
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install torbrowser
      become: true
      community.general.pacman:
        name: torbrowser-launcher
        state: present
      tags:
        - arch
  
