- hosts: localhost
  roles:
    - role: "../roles/linuxenv/tasks/main.yml"
  tasks:
    - name: Install torbrowser
      apt:
        pkg:
           - torbrowser-launcher
        state: latest
        update_cache: true
      tags:
        - deb

    - name: Install torbrowser
      pacman:
        name: torbrowser-launcher
        state: latest
        update_cache: true
      tags:
        - arch
  
